### ISSUE TITLE
Chapter 9 - Compile errors

### ISSUE THREAD

**Issue by guylangston** [yfain/getts#1]
Did a clean git clone, with no edits/changes

![image](https://user-images.githubusercontent.com/3845440/66639996-ea3c5d80-ec0f-11e9-8dda-0e77c39f1d3e.png)

**Comment by antonmoiseev** [comment]
It failed because `tsc` version globally installed on your machine is different from the one we use in the repo. And the latest TypeScript version is incompatible with the `@types/node` that we use. If you run `npx tsc` (which runs project-local `tsc`) it completes successfully.

I've upgraded all of the packages to the latest version, so it should work fine now with TypeScript 3.6 as well.
